Update deployment10tierwebapp.yaml

diff --git a/deployment10tierwebapp.yaml b/deployment10tierwebapp.yaml
--- a/deployment10tierwebapp.yaml
+++ b/deployment10tierwebapp.yaml
@@ -1,4 +1,3 @@
----
 apiVersion: apps/v1
 kind: Deployment
 metadata:
@@ -38,12 +37,12 @@ spec:
           value: "1"
         readinessProbe:
           periodSeconds: 5
-          exec:
-            command: ["/bin/grpc_health_probe", "-addr=:8080"]
+          grpc:
+            port: 8080
         livenessProbe:
           periodSeconds: 5
-          exec:
-            command: ["/bin/grpc_health_probe", "-addr=:8080"]
+          grpc:
+            port: 8080
         resources:
           requests:
             cpu: 100m
@@ -64,9 +63,7 @@ spec:
   - name: grpc
     port: 5000
     targetPort: 8080
-
 ---
-
 apiVersion: apps/v1
 kind: Deployment
 metadata:
@@ -81,17 +78,29 @@ spec:
         app: checkoutservice
     spec:
       serviceAccountName: default
+      securityContext:
+        fsGroup: 1000
+        runAsGroup: 1000
+        runAsNonRoot: true
+        runAsUser: 1000
       containers:
         - name: server
+          securityContext:
+            allowPrivilegeEscalation: false
+            capabilities:
+              drop:
+                - ALL
+            privileged: false
+            readOnlyRootFilesystem: true
           image: cloudrohith98/checkoutservice:latest
           ports:
           - containerPort: 5050
           readinessProbe:
-            exec:
-              command: ["/bin/grpc_health_probe", "-addr=:5050"]
+            grpc:
+              port: 5050
           livenessProbe:
-            exec:
-              command: ["/bin/grpc_health_probe", "-addr=:5050"]
+            grpc:
+              port: 5050
           env:
           - name: PORT
             value: "5050"
@@ -127,10 +136,7 @@ spec:
   - name: grpc
     port: 5050
     targetPort: 5050
-
-
 ---
-
 apiVersion: apps/v1
 kind: Deployment
 metadata:
@@ -146,19 +152,31 @@ spec:
     spec:
       serviceAccountName: default
       terminationGracePeriodSeconds: 5
+      securityContext:
+        fsGroup: 1000
+        runAsGroup: 1000
+        runAsNonRoot: true
+        runAsUser: 1000
       containers:
       - name: server
+        securityContext:
+          allowPrivilegeEscalation: false
+          capabilities:
+            drop:
+              - ALL
+          privileged: false
+          readOnlyRootFilesystem: true
         image: cloudrohith98/recommendationservice:latest
         ports:
         - containerPort: 8080
         readinessProbe:
           periodSeconds: 5
-          exec:
-            command: ["/bin/grpc_health_probe", "-addr=:8080"]
+          grpc:
+            port: 8080
         livenessProbe:
           periodSeconds: 5
-          exec:
-            command: ["/bin/grpc_health_probe", "-addr=:8080"]
+          grpc:
+            port: 8080
         env:
         - name: PORT
           value: "8080"
@@ -186,9 +204,7 @@ spec:
   - name: grpc
     port: 8080
     targetPort: 8080
-
 ---
-
 apiVersion: apps/v1
 kind: Deployment
 metadata:
@@ -205,8 +221,20 @@ spec:
         sidecar.istio.io/rewriteAppHTTPProbers: "true"
     spec:
       serviceAccountName: default
+      securityContext:
+        fsGroup: 1000
+        runAsGroup: 1000
+        runAsNonRoot: true
+        runAsUser: 1000
       containers:
         - name: server
+          securityContext:
+            allowPrivilegeEscalation: false
+            capabilities:
+              drop:
+                - ALL
+            privileged: false
+            readOnlyRootFilesystem: true
           image: cloudrohith98/frontend:latest
           ports:
           - containerPort: 8080
@@ -266,7 +294,7 @@ kind: Service
 metadata:
   name: frontend
 spec:
-  type: NodePort
+  type: ClusterIP
   selector:
     app: frontend
   ports:
@@ -286,9 +314,7 @@ spec:
   - name: http
     port: 80
     targetPort: 8080
-
 ---
-
 apiVersion: apps/v1
 kind: Deployment
 metadata:
@@ -304,8 +330,20 @@ spec:
     spec:
       serviceAccountName: default
       terminationGracePeriodSeconds: 5
+      securityContext:
+        fsGroup: 1000
+        runAsGroup: 1000
+        runAsNonRoot: true
+        runAsUser: 1000
       containers:
       - name: server
+        securityContext:
+          allowPrivilegeEscalation: false
+          capabilities:
+            drop:
+              - ALL
+          privileged: false
+          readOnlyRootFilesystem: true
         image: cloudrohith98/paymentservice:latest
         ports:
         - containerPort: 50051
@@ -315,11 +353,11 @@ spec:
         - name: DISABLE_PROFILER
           value: "1"
         readinessProbe:
-          exec:
-            command: ["/bin/grpc_health_probe", "-addr=:50051"]
+          grpc:
+            port: 50051
         livenessProbe:
-          exec:
-            command: ["/bin/grpc_health_probe", "-addr=:50051"]
+          grpc:
+            port: 50051
         resources:
           requests:
             cpu: 100m
@@ -340,9 +378,7 @@ spec:
   - name: grpc
     port: 50051
     targetPort: 50051
-
 ---
-
 apiVersion: apps/v1
 kind: Deployment
 metadata:
@@ -358,8 +394,20 @@ spec:
     spec:
       serviceAccountName: default
       terminationGracePeriodSeconds: 5
+      securityContext:
+        fsGroup: 1000
+        runAsGroup: 1000
+        runAsNonRoot: true
+        runAsUser: 1000
       containers:
       - name: server
+        securityContext:
+          allowPrivilegeEscalation: false
+          capabilities:
+            drop:
+              - ALL
+          privileged: false
+          readOnlyRootFilesystem: true
         image: cloudrohith98/productcatalogservice:latest
         ports:
         - containerPort: 3550
@@ -369,11 +417,11 @@ spec:
         - name: DISABLE_PROFILER
           value: "1"
         readinessProbe:
-          exec:
-            command: ["/bin/grpc_health_probe", "-addr=:3550"]
+          grpc:
+            port: 3550
         livenessProbe:
-          exec:
-            command: ["/bin/grpc_health_probe", "-addr=:3550"]
+          grpc:
+            port: 3550
         resources:
           requests:
             cpu: 100m
@@ -394,9 +442,7 @@ spec:
   - name: grpc
     port: 3550
     targetPort: 3550
-
 ---
-
 apiVersion: apps/v1
 kind: Deployment
 metadata:
@@ -412,8 +458,20 @@ spec:
     spec:
       serviceAccountName: default
       terminationGracePeriodSeconds: 5
+      securityContext:
+        fsGroup: 1000
+        runAsGroup: 1000
+        runAsNonRoot: true
+        runAsUser: 1000
       containers:
       - name: server
+        securityContext:
+          allowPrivilegeEscalation: false
+          capabilities:
+            drop:
+              - ALL
+          privileged: false
+          readOnlyRootFilesystem: true
         image: cloudrohith98/cartservice:latest
         ports:
         - containerPort: 7070
@@ -429,13 +487,13 @@ spec:
             memory: 128Mi
         readinessProbe:
           initialDelaySeconds: 15
-          exec:
-            command: ["/bin/grpc_health_probe", "-addr=:7070", "-rpc-timeout=5s"]
+          grpc:
+            port: 7070
         livenessProbe:
           initialDelaySeconds: 15
           periodSeconds: 10
-          exec:
-            command: ["/bin/grpc_health_probe", "-addr=:7070", "-rpc-timeout=5s"]
+          grpc:
+            port: 7070
 ---
 apiVersion: v1
 kind: Service
@@ -449,9 +507,7 @@ spec:
   - name: grpc
     port: 7070
     targetPort: 7070
-
 ---
-
 apiVersion: apps/v1
 kind: Deployment
 metadata:
@@ -471,6 +527,34 @@ spec:
       serviceAccountName: default
       terminationGracePeriodSeconds: 5
       restartPolicy: Always
+      securityContext:
+        fsGroup: 1000
+        runAsGroup: 1000
+        runAsNonRoot: true
+        runAsUser: 1000
+      initContainers:
+      - command:
+        - /bin/sh
+        - -exc
+        - |
+          echo "Init container pinging frontend: ${FRONTEND_ADDR}..."
+          STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
+          if test $STATUSCODE -ne 200; then
+              echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
+              exit 1
+          fi
+        name: frontend-check
+        securityContext:
+          allowPrivilegeEscalation: false
+          capabilities:
+            drop:
+              - ALL
+          privileged: false
+          readOnlyRootFilesystem: true
+        image: busybox:latest
+        env:
+        - name: FRONTEND_ADDR
+          value: "frontend:80"
       containers:
       - name: main
         securityContext:
@@ -493,9 +577,7 @@ spec:
           limits:
             cpu: 500m
             memory: 512Mi
-
 ---
-
 apiVersion: apps/v1
 kind: Deployment
 metadata:
@@ -511,8 +593,20 @@ spec:
     spec:
       serviceAccountName: default
       terminationGracePeriodSeconds: 5
+      securityContext:
+        fsGroup: 1000
+        runAsGroup: 1000
+        runAsNonRoot: true
+        runAsUser: 1000
       containers:
       - name: server
+        securityContext:
+          allowPrivilegeEscalation: false
+          capabilities:
+            drop:
+              - ALL
+          privileged: false
+          readOnlyRootFilesystem: true
         image: cloudrohith98/currencyservice:latest
         ports:
         - name: grpc
@@ -523,11 +617,11 @@ spec:
         - name: DISABLE_PROFILER
           value: "1"
         readinessProbe:
-          exec:
-            command: ["/bin/grpc_health_probe", "-addr=:7000"]
+          grpc:
+            port: 7000
         livenessProbe:
-          exec:
-            command: ["/bin/grpc_health_probe", "-addr=:7000"]
+          grpc:
+            port: 7000
         resources:
           requests:
             cpu: 100m
@@ -548,9 +642,7 @@ spec:
   - name: grpc
     port: 7000
     targetPort: 7000
-
 ---
-
 apiVersion: apps/v1
 kind: Deployment
 metadata:
@@ -565,8 +657,20 @@ spec:
         app: shippingservice
     spec:
       serviceAccountName: default
+      securityContext:
+        fsGroup: 1000
+        runAsGroup: 1000
+        runAsNonRoot: true
+        runAsUser: 1000
       containers:
       - name: server
+        securityContext:
+          allowPrivilegeEscalation: false
+          capabilities:
+            drop:
+              - ALL
+          privileged: false
+          readOnlyRootFilesystem: true
         image: cloudrohith98/shippingservice:latest
         ports:
         - containerPort: 50051
@@ -577,11 +681,11 @@ spec:
           value: "1"
         readinessProbe:
           periodSeconds: 5
-          exec:
-            command: ["/bin/grpc_health_probe", "-addr=:50051"]
+          grpc:
+            port: 50051
         livenessProbe:
-          exec:
-            command: ["/bin/grpc_health_probe", "-addr=:50051"]
+          grpc:
+            port: 50051
         resources:
           requests:
             cpu: 100m
@@ -602,9 +706,7 @@ spec:
   - name: grpc
     port: 50051
     targetPort: 50051
-
 ---
-
 apiVersion: apps/v1
 kind: Deployment
 metadata:
@@ -618,8 +720,20 @@ spec:
       labels:
         app: redis-cart
     spec:
+      securityContext:
+        fsGroup: 1000
+        runAsGroup: 1000
+        runAsNonRoot: true
+        runAsUser: 1000
       containers:
       - name: redis
+        securityContext:
+          allowPrivilegeEscalation: false
+          capabilities:
+            drop:
+              - ALL
+          privileged: false
+          readOnlyRootFilesystem: true
         image: redis:alpine
         ports:
         - containerPort: 6379
@@ -657,9 +771,7 @@ spec:
   - name: tcp-redis
     port: 6379
     targetPort: 6379
-
 ---
-
 apiVersion: apps/v1
 kind: Deployment
 metadata:
@@ -675,8 +787,20 @@ spec:
     spec:
       serviceAccountName: default
       terminationGracePeriodSeconds: 5
+      securityContext:
+        fsGroup: 1000
+        runAsGroup: 1000
+        runAsNonRoot: true
+        runAsUser: 1000
       containers:
       - name: server
+        securityContext:
+          allowPrivilegeEscalation: false
+          capabilities:
+            drop:
+              - ALL
+          privileged: false
+          readOnlyRootFilesystem: true
         image: cloudrohith98/adservice:latest
         ports:
         - containerPort: 9555
@@ -693,13 +817,13 @@ spec:
         readinessProbe:
           initialDelaySeconds: 20
           periodSeconds: 15
-          exec:
-            command: ["/bin/grpc_health_probe", "-addr=:9555"]
+          grpc:
+            port: 9555
         livenessProbe:
           initialDelaySeconds: 20
           periodSeconds: 15
-          exec:
-            command: ["/bin/grpc_health_probe", "-addr=:9555"]
+          grpc:
+            port: 9555
 ---
 apiVersion: v1
 kind: Service
@@ -713,87 +837,3 @@ spec:
   - name: grpc
     port: 9555
     targetPort: 9555
-
-
-
-
-
-Deployments:
-emailservice Deployment:
-
-Service: emailservice
-Container Image: cloudrohith98/emailservice:latest
-Exposes a gRPC service on port 8080.
-Resource limits: CPU: 100m, Memory: 64Mi
-checkoutservice Deployment:
-
-Service: checkoutservice
-Container Image: cloudrohith98/checkoutservice:latest
-Exposes a gRPC service on port 5050.
-Dependencies on other services like productcatalogservice, shippingservice, etc.
-Resource limits: CPU: 100m, Memory: 64Mi
-recommendationservice Deployment:
-
-Service: recommendationservice
-Container Image: cloudrohith98/recommendationservice:latest
-Exposes a gRPC service on port 8080.
-Dependencies on productcatalogservice.
-Resource limits: CPU: 100m, Memory: 220Mi
-frontend Deployment:
-
-Service: frontend
-Container Image: cloudrohith98/frontend:latest
-Exposes HTTP on port 80.
-Dependencies on various services.
-Resource limits: CPU: 100m, Memory: 64Mi
-paymentservice Deployment:
-
-Service: paymentservice
-Container Image: cloudrohith98/paymentservice:latest
-Exposes a gRPC service on port 50051.
-Resource limits: CPU: 100m, Memory: 64Mi
-productcatalogservice Deployment:
-
-Service: productcatalogservice
-Container Image: cloudrohith98/productcatalogservice:latest
-Exposes a gRPC service on port 3550.
-Resource limits: CPU: 100m, Memory: 64Mi
-cartservice Deployment:
-
-Service: cartservice
-Container Image: cloudrohith98/cartservice:latest
-Exposes a gRPC service on port 7070.
-Dependencies on redis-cart.
-Resource limits: CPU: 200m, Memory: 64Mi
-loadgenerator Deployment:
-
-Service: loadgenerator
-Container Image: cloudrohith98/loadgenerator:latest
-Generates load on the frontend service.
-Resource limits: CPU: 300m, Memory: 256Mi
-currencyservice Deployment:
-
-Service: currencyservice
-Container Image: cloudrohith98/currencyservice:latest
-Exposes a gRPC service on port 7000.
-Resource limits: CPU: 100m, Memory: 64Mi
-shippingservice Deployment:
-
-Service: shippingservice
-Container Image: cloudrohith98/shippingservice:latest
-Exposes a gRPC service on port 50051.
-Resource limits: CPU: 100m, Memory: 64Mi
-redis-cart Deployment:
-
-Service: redis-cart
-Container Image: redis:alpine
-Acts as a Redis database for the cartservice.
-Resource limits for the Redis container.
-adservice Deployment:
-
-Service: adservice
-Container Image: cloudrohith98/adservice:latest
-Exposes a gRPC service on port 9555.
-Resource limits: CPU: 200m, Memory: 180Mi
-
-
